services:
  - type: pserv
    name: sims-db
    env: docker
    dockerContext: database
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: password
      - key: MYSQL_DATABASE
        value: sims

  - type: web
    name: sims-backend
    env: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://sims-db/sims
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: password

  - type: web
    name: sims-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: sims-backend
          type: web
          property: host
